language: node_js
node_js: 10
install:
- npm ci
- cd catalog-app && npm ci
- cd ../ci-app && npm ci
- cd ../ci-status-app && npm ci
- cd ../
script:
  - cd ci-app && npm test
cache:
  directories:
  - "$HOME/.npm"
