apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apic-ci-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: apic-ci-global
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
  labels:
    app: apic-ci
spec:
  # backend:
  #   serviceName: apic-ci-frontend
  #   servicePort: 8080

  rules:
  - host: ci.advancedrestclient.com
    http:
      paths:
      - backend:
          serviceName: apic-ci-frontend
          servicePort: 8080
  - host: api.advancedrestclient.com
    http:
      paths:
      - backend:
          serviceName: arc-api
          servicePort: 8080
  - host: catalog.advancedrestclient.com
    http:
      paths:
      - backend:
          serviceName: apic-catalog
          servicePort: 8080

# https://github.com/ahmetb/gke-letsencrypt/blob/master/50-get-a-certificate.md
  tls:
  - secretName: ci-advancedrestclient-com-tls
    hosts:
    - ci.advancedrestclient.com
  - secretName: api-advancedrestclient-com-tls
    hosts:
    - api.advancedrestclient.com
  - secretName: catalog-advancedrestclient-com-tls
    hosts:
    - catalog.advancedrestclient.com
---
apiVersion: v1
kind: Service
metadata:
  name: apic-ci-status
  labels:
    app: apic-ci
spec:
  type: NodePort
  selector:
    app: apic-ci
    tier: frontend
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: arc-api
  labels:
    app: apic-ci-api
spec:
  type: NodePort
  selector:
    app: arc-api
    tier: api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apic-catalog
  labels:
    app: apic-catalog
spec:
  type: NodePort
  selector:
    app: apic-catalog-frontend
    tier: frontend
  ports:
  - port: 8080
    targetPort: 8080
